### ISSUE TITLE
Not good performance in an open source dataset

### ISSUE THREAD

**Issue by city19992** [hugoycj/Instant-angelo#31]
Nice job. I tested your code on an open source which could be download from https://doc.arcgis.com/en/drone2map/latest/help/sample-data.htm.

But the reconstructed geometry is not so reasonable. Is there any possible reason?

![it50000-1](https://github.com/hugoycj/Instant-angelo/assets/53545756/92921a67-9d5e-4dda-940b-ed356fe4a959)
![it50000-3](https://github.com/hugoycj/Instant-angelo/assets/53545756/b42b565a-555b-4ea2-87a3-35f777eaa422)

The first one was trained based on neuralangelo-colmap_sparse-50k.yaml. In the second experiment, I centered and scaled the 3D point cloud into NDC space and set the sampling range of ray marching to the outer bounding box of the point cloud. Other settings are the same. But both of the results are not so good.

**Comment by hugoycj** [comment]
Thank you for the results! I will review the data in more detail

**Comment by hugoycj** [comment]
Sorry to bother you, I fail to reproduce the issues. The results seem OK on my side. 

![2](https://github.com/hugoycj/Instant-angelo/assets/40767265/6a8c8ece-e27d-43c2-85d5-0fb1316ef96a)
![1](https://github.com/hugoycj/Instant-angelo/assets/40767265/30d46660-2ea9-41d9-b7ce-0174a56ac649)

**Comment by city19992** [comment]
Thank you so much for the reply. I will try it later.

**Comment by hugoycj** [comment]
By the way, the current results are generated using the `neuralangelo-colmap_sparse.yaml` configuration. We have temporarily discarded the `neuralangelo-colmap_sparse-50k.yaml` since we found limited quality improvement and it is less robust than the `neuralangelo-colmap_sparse.yaml`. For detailed reconstruction, we sincerely recommend the `neuralangelo-colmap_dense.yaml` which utilizes the dense point cloud from MVSNet or even from other MVS tools like drone2map as a prior.
